### PR TITLE
doc: improve license in readme

### PR DESCRIPTION
**Pull request by jlorgal**

### CODE REVIEW

**Comment by contint** [comment]
Can one of the admins verify this patch?

**Comment by jlorgal** [comment]
Test

**Comment by jlorgal** [comment]
Test

**Comment by jlorgal** [comment]
Test

**Comment by jlorgal** [comment]
Test

**Comment by jlorgal** [comment]
Test

**Comment by jlorgal** [comment]
Test

**Comment by jlorgal** [comment]
Test

**Comment by jlorgal** [comment]
Test

**Comment by jlorgal** [comment]
Test

**Comment by jlorgal** [comment]
Test

**Comment by jlorgal** [comment]
Test

**Comment by jlorgal** [comment]
Test

**Comment by jlorgal** [comment]
test

**Pull request merged**
